-- claim_attachments: file deliverables submitted as part of a claim.
--
-- Phase 0.2a of the post-genericization roadmap (TODO.md §9 → Phase 0).
-- Companion to 0035_submissions_storage_bucket.sql, which created the
-- `submissions` Storage bucket. This migration adds the relational
-- index of which Storage objects belong to which claim.
--
-- Why a separate table (not a JSONB column on claims):
--   * Lets us drop attachments individually (e.g. on resubmit, on
--     claim cancellation, or via a future "rotate stale assets"
--     cleanup) without rewriting the claim row.
--   * Lets us index/query by claim_id for the "Pending review" admin
--     surface that lists a claim with its files.
--   * `submission_url` already covers the single hosted-link case
--     (YouTube / Vimeo / IG); this table only carries native uploads.
--
-- Attachment lifecycle:
--   * INSERT happens inside the `submitClaim` server action (Phase
--     0.2a), which writes both the storage.objects row and the
--     claim_attachments row using the service-role client. Permission
--     is checked in the action; there is intentionally no INSERT RLS
--     policy here.
--   * SELECT goes through RLS — both the claim's creator and any org
--     member of the claim's org can read the metadata. Actual file
--     bytes still need a signed URL (the Storage bucket from 0035 is
--     private), generated by a server action that re-checks the same
--     permissions.
--   * DELETE cascades from claims (via FK), so cancelling or deleting
--     a claim wipes its attachment rows automatically. The Storage
--     objects themselves are NOT auto-deleted by this — a future
--     cleanup job (or the cancel/reset-claim server action) needs to
--     remove the bucket objects under the same path prefix.

CREATE TABLE claim_attachments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL REFERENCES claims(id) ON DELETE CASCADE,
  -- Path inside the `submissions` bucket from 0035, e.g.
  -- `{user_id}/{claim_id}/{timestamp}-{filename}`. UNIQUE so a buggy
  -- double-insert would error rather than silently duplicate.
  storage_path text NOT NULL UNIQUE,
  -- Original filename as the creator uploaded it. Used in the UI
  -- ("submission_v2_final.mp4") — not used for path resolution.
  filename text NOT NULL,
  mime_type text NOT NULL,
  -- Bytes. integer is enough up to 2 GiB; the bucket cap is 250 MB
  -- so we're well within range.
  file_size integer NOT NULL CHECK (file_size > 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX claim_attachments_claim_id_idx
  ON claim_attachments (claim_id);

ALTER TABLE claim_attachments ENABLE ROW LEVEL SECURITY;

-- The claim's creator can read their own attachment metadata.
CREATE POLICY "Claim creator reads own attachments"
  ON claim_attachments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM claims
      WHERE claims.id = claim_attachments.claim_id
        AND claims.user_id = auth.uid()
    )
  );

-- Any active member of the brief's org (admin OR member role) can read
-- attachment metadata. Mirrors the broadened claim-read policies from
-- 0034 — members handle day-to-day brief/claim ops, so they need to
-- see submitted assets.
CREATE POLICY "Org members read claim attachments"
  ON claim_attachments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM claims
      WHERE claims.id = claim_attachments.claim_id
        AND is_org_member(claims.org_id)
    )
  );

-- No INSERT / UPDATE / DELETE policies — those happen exclusively via
-- the service-role client behind server actions. See the lifecycle
-- comment at the top.
